language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: kUsXxtAnw9/vawqIoIjFkDZrJaZvm2PqtfulNS4dXfhxW3U5KWuVdl94N58mZCtCVNQFFAf/saeY80a5jCw8p3e+wviI2q596pxltkX5fv127GhyfubPNwYi45qkgha2+M5PDoQOw4O58+LuSRJcbh5w2CJ2Q9YFFfnGKvFp2dxnSNFkEJwHg21J4wbNzpKPziyGJ9MctcbVeR954yolvup3tN00tD+l7PQ+m9mjVL9duipZN5Bcaw6EZvAT/JlLw6HbdDsaoqv4+InLxt4A8gaRt8uStmEU44+n/eKfhVnXYScyo6RfnBcsUryc7bHL/p/mlCqr+6c86DrAIU4ZhmGESqmpJ2y3N3j7Q2d0y7f0e2OKQss8gmpXCte68SinxAZnrHzpNKhHeQaGt0QseIJl48XdD7OHqb7tOhZwAx5Z4yfXfro5YYUiU061V+ega8SrMshR6xswJ8iQaJd6409o1O5v0yNj9aQm8CMga9Fioas/O4xoY0m5HqkQVHcGDRrHh7UEZ/+352CGcGZoKHMY1fJ1gmY+OGWTyKhWk8shMKYyK4J4pC5TOYYxMPLiXktPPyq2Hi2NSkldMFBk2TMy8sYzDWd2iYDIPCKDRBuWGBlaniaaR8Abymk61+awuvMrfrW3dwlvfN6cucSjRPrj+iytuYpk0AU/3l3pBS0=
  app: react-trello-testing
  on:
    repo: Richardek/react-trello-testing
