language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: v4x4SIi76c5qQYcCxibpjlTX3wruXEd98hZTI9k4QTwfTSQuBhhQjcnAFGOfzQ87xAOCiqY0KJssuF6L0UbrK+If1qR8l3uDZRIvhZysU/uOtYs9tuDPc+KLdIeCCo3eokWIRSjs43Q9Y8GofrIp/1TvVLbM3BlIU0SUa4+nUDUOXeWPE2HqaRLreyoWYr7yQxBIG9/WU7DT2LrsmHpL2rphXmhQvA71P3S8kfXWNJlBmdU42iwv6hOSBJH39s5O++hUnhTDCHvliBA1YRUPGrAKof5EWL/vTPODy6i9EeaMizM1L4Q68zmPF9G6zTUIPkSyYtHwJmw8WckEAsWCmuO4DCt+wJyyDagnNQFyi4lfWk1TACornjg/JPdld0ILxBBvnRv8JOenoTG5PAgMuLb6eDVBX5cj7Ve5tJrp5DmjnlgNAVDc48OxFfkDU4wH/Uthm+Zh9xX8hQWILXp0NsW52YQbZClIA3Ng9bukSJPE1O1IboI6nSub6P81fhNi++A16CT03Y8QP+0OloUyftENog7ZT1DvDNOZenwu/6GTKiuwgXI4RGeltjIc86ocSaDwKv5WEE16EMeExPs7cDp4FhBD9ahdBGy8cSNXNQmLJfraC9YS5DBPKx5gnXOnzbxw+KFI+4XUt6vkblOliwzmYUaPq0w16VERrb7i0g8=
  app: react-trello-testing
  on:
    repo: Richardek/react-trello-testing
